#!/bin/sh

OUTPUT_FILE="src/build_time.c"

BUILD_TIME=`date '+%Y-%m-%d %H:%M:%S'`

if [ $? -ne 0 ]; then
	BUILD_TIME="UNKNOWN BUILD TIME"
fi

REVISION_TXT=`svn info|egrep "^Revision:"`

REVISION_INT=`echo ${REVISION_TXT}|sed -e s/^Revision://`

if [ -z "${REVISION_INT}" ]; then
	echo -e "\n\n$0 - ERROR: can't SVN get revision info\n\n"
	exit 1
fi

cat << ENDOFFILE > ${OUTPUT_FILE}

/* Do NOT edit this file! His content is created automatically from $0 */

char* build_time_get ( void ) { return "${BUILD_TIME}"; }

char* build_time_get_revision_txt ( void ) { return "${REVISION_TXT}"; }

int build_time_get_revision_int ( void ) { return ${REVISION_INT}; }

/* end of ${OUTPUT_FILE} */

ENDOFFILE

exit $?
