#!/bin/sh

OUTPUT_FILE="src/build_time.c"

BUILD_TIME=`date '+%Y-%m-%d %H:%M:%S'`

if [ $? -ne 0 ]; then
	BUILD_TIME="UNKNOWN BUILD TIME"
fi

REVISION_INT=`git rev-list --count --first-parent HEAD`

if [ -z "${REVISION_INT}" ]; then
	echo -e "\n\n$0 - ERROR: can't get git revision info\n\n"
	exit 1
fi

LAST_COMMIT=`git show -s --pretty=format:"%H - %s"`

cat << ENDOFFILE > ${OUTPUT_FILE}

/* Do NOT edit this file! His content is created automatically from $0 */

char* build_time_get ( void ) { return "${BUILD_TIME}"; }

char* build_time_get_revision_txt ( void ) { return "${LAST_COMMIT}"; }

int build_time_get_revision_int ( void ) { return ${REVISION_INT}; }

/* end of ${OUTPUT_FILE} */

ENDOFFILE

exit $?
